In [11]:
# importing important libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from ydata_profiling import ProfileReport

ImportError: cannot import name 'Any' from 'typing_extensions' (C:\Users\ankit\anaconda3\lib\site-packages\typing_extensions.py)

In [2]:
crime_data = pd.read_csv("Crime_Data_from_2020_to_Present.csv")
crime_data.head() # uploading data into data frame.

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,10304468,01-08-2020,01-08-2020,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,...,AO,Adult Other,624.0,NaN,NaN,NaN,1100 W 39TH PL,NaN,34.0141,-118.2978
1,190101086,01-02-2020,01-01-2020,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,...,IC,Invest Cont,624.0,NaN,NaN,NaN,700 S HILL ST,NaN,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,...,AA,Adult Arrest,845.0,NaN,NaN,NaN,200 E 6TH ST,NaN,34.0448,-118.2474
3,191501505,01-01-2020,01-01-2020,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),...,IC,Invest Cont,745.0,998.0,NaN,NaN,5400 CORTEEN PL,NaN,34.1685,-118.4019
4,191921269,01-01-2020,01-01-2020,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",...,IC,Invest Cont,740.0,NaN,NaN,NaN,14400 TITUS ST,NaN,34.2198,-118.4468

In [3]:
crime_data.isna().sum() # checking for na values

DR_NO                  0
Date Rptd              0
DATE OCC               0
TIME OCC               0
AREA                   0
AREA NAME              0
Rpt Dist No            0
Part 1-2               0
Crm Cd                 0
Crm Cd Desc            0
Mocodes           114148
Vict Age               0
Vict Sex          108529
Vict Descent      108537
Premis Cd             10
Premis Desc          488
Weapon Used Cd    537498
Weapon Desc       537498
Status                 0
Status Desc            0
Crm Cd 1              10
Crm Cd 2          764505
Crm Cd 3          823173
Crm Cd 4          825151
LOCATION               0
Cross Street      693343
LAT                    0
LON                    0
dtype: int64

In [4]:
column_seperate=["Mocodes","Vict Descent","Vict Sex","Weapon Used Cd","Weapon Desc","Cross Street","Crm Cd 1","Crm Cd 2","Crm Cd 3","Crm Cd 4"]
# separating columns with high na values to secondary data frame. (maybe they can be used at somepoint during project)

In [5]:
crime_data_1 = crime_data.drop(columns = column_seperate) # data frame with columns most appropriate at this point.
# we may need to change them as we advance further.

In [6]:
crime_data_1.isna().sum() # checking na with new df.

DR_NO            0
Date Rptd        0
DATE OCC         0
TIME OCC         0
AREA             0
AREA NAME        0
Rpt Dist No      0
Part 1-2         0
Crm Cd           0
Crm Cd Desc      0
Vict Age         0
Premis Cd       10
Premis Desc    488
Status           0
Status Desc      0
LOCATION         0
LAT              0
LON              0
dtype: int64

In [7]:
crime_data_1["Premis Desc"].fillna("unknown", inplace = True)

In [8]:
crime_data_1 = crime_data_1.dropna(subset=["Premis Cd"])

In [9]:
crime_data_1.isna().sum() # df with zero na

DR_NO          0
Date Rptd      0
DATE OCC       0
TIME OCC       0
AREA           0
AREA NAME      0
Rpt Dist No    0
Part 1-2       0
Crm Cd         0
Crm Cd Desc    0
Vict Age       0
Premis Cd      0
Premis Desc    0
Status         0
Status Desc    0
LOCATION       0
LAT            0
LON            0
dtype: int64

In [12]:
crime_data_1 # looking into data with no na

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Vict Age,Premis Cd,Premis Desc,Status,Status Desc,LOCATION,LAT,LON
0,10304468,01-08-2020,01-08-2020,2230,3,Southwest,377,2,624,BATTERY - SIMPLE ASSAULT,36,501.0,SINGLE FAMILY DWELLING,AO,Adult Other,1100 W 39TH PL,34.0141,-118.2978
1,190101086,01-02-2020,01-01-2020,330,1,Central,163,2,624,BATTERY - SIMPLE ASSAULT,25,102.0,SIDEWALK,IC,Invest Cont,700 S HILL ST,34.0459,-118.2545
2,200110444,04/14/2020 12:00:00 AM,02/13/2020 12:00:00 AM,1200,1,Central,155,2,845,SEX OFFENDER REGISTRANT OUT OF COMPLIANCE,0,726.0,POLICE FACILITY,AA,Adult Arrest,200 E 6TH ST,34.0448,-118.2474
3,191501505,01-01-2020,01-01-2020,1730,15,N Hollywood,1543,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),76,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,5400 CORTEEN PL,34.1685,-118.4019
4,191921269,01-01-2020,01-01-2020,415,19,Mission,1998,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",31,409.0,BEAUTY SUPPLY STORE,IC,Invest Cont,14400 TITUS ST,34.2198,-118.4468
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
825207,231604807,01/27/2023 12:00:00 AM,01/26/2023 12:00:00 AM,1800,16,Foothill,1663,2,740,"VANDALISM - FELONY ($400 & OVER, ALL CHURCH VA...",23,122.0,"VEHICLE, PASSENGER/TRUCK",IC,Invest Cont,12500 BRANFORD ST,34.2466,-118.4054
825208,231606525,03/22/2023 12:00:00 AM,03/22/2023 12:00:00 AM,1000,16,Foothill,1602,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",25,102.0,SIDEWALK,IC,Invest Cont,12800 FILMORE ST,34.2790,-118.4116
825209,231210064,04-12-2023,04-12-2023,1630,12,77th Street,1239,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",29,222.0,LAUNDROMAT,IC,Invest Cont,6100 S VERMONT AV,33.9841,-118.2915
825210,230115220,07-02-2023,07-01-2023,1,1,Central,154,1,352,PICKPOCKET,24,735.0,NIGHT CLUB (OPEN EVENINGS ONLY),IC,Invest Cont,500 S MAIN ST,34.0467,-118.2485
825211,230906458,03-05-2023,03-05-2023,900,9,Van Nuys,914,2,745,VANDALISM - MISDEAMEANOR ($399 OR UNDER),53,502.0,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,14500 HARTLAND ST,34.1951,-118.4487

In [13]:
pr_df1 = ProfileReport(crime_data_1)
pr_df1 # trying something new........ydata_profiling.
#  it hepls to draw lot of insights from data....everything for EDA at one place.
# can be of

NameError: name 'ProfileReport' is not defined